name: Release
on:
  push:
    branches: "!*"
    tags:
    - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Release
        run: |
          composer install
          cd .. && cp -R ps-utanvet-ellenor utanvetellenor
          zip -r0 utanvetellenor.zip utanvetellenor -x "utanvetellenor/.git/*" "utanvetellenor/.github/*" "utanvetellenor/.auto-changelog" "utanvetellenor/.gitignore" "utanvetellenor/.composer-version.js" "utanvetellenor/package.json" "utanvetellenor/package-lock.json"
          mv utanvetellenor.zip ~/utanvetellenor.zip
        
      - name: Upload Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "/home/runner/utanvetellenor.zip"
          tags: true
          draft: false
          update_latest_release: true
