# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, create-release-action ]
  pull_request:
    branches: [ main, create-release-action ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Create drag'n'drop installable PrestaShop package
        run: |
          cd .. && cp -R ps-utanvet-ellenor utanvetellenor
          zip -r0 utanvetellenor.zip utanvetellenor -x ".git/*" ".github/*"
          rm -Rf utanvetellenor
